services:
  stats-server:
    build: ./stats/stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=stats
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dbuser", "-d", "stats"]
      interval: 5s
      timeout: 5s
      retries: 10
